import cv2
import numpy as np
from PIL import Image
import torch
import lpips
from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
import base64
import io

app = Flask(__name__)
CORS(app)
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.config['MAX_CONTENT_LENGTH'] = 1 * 1024 * 1024 * 1024  # 1GB

@app.after_request
def add_no_cache(response):
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response

loss_fn_alex = None

def init_lpips():
    global loss_fn_alex
    if loss_fn_alex is None:
        loss_fn_alex = lpips.LPIPS(net='alex')
    return loss_fn_alex

def pil_to_tensor(img):
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = np.array(img).astype(np.float32) / 255.0
    img = torch.from_numpy(img).permute(2, 0, 1).unsqueeze(0)
    return img

def calculate_msssim(img1, img2):
    from scipy.ndimage import gaussian_filter

    img1 = img1.astype(np.float64)
    img2 = img2.astype(np.float64)

    levels = 5
    weights = [0.0448, 0.2856, 0.3001, 0.2363, 0.1333]
    mssim = np.array([])

    for _ in range(levels):
        mssim = np.append(mssim, ssim_single_scale(img1, img2))
        img1 = gaussian_filter(img1, [1.5, 1.5, 0])
        img2 = gaussian_filter(img2, [1.5, 1.5, 0])

    mssim_values = mssim[:len(weights)]
    return np.prod(np.power(mssim_values, weights))

def ssim_single_scale(img1, img2):
    C1 = (0.01 * 255) ** 2
    C2 = (0.03 * 255) ** 2

    img1 = img1.astype(np.float64)
    img2 = img2.astype(np.float64)
    kernel = cv2.getGaussianKernel(11, 1.5)
    window = np.outer(kernel, kernel.transpose())

    mu1 = cv2.filter2D(img1, -1, window)[5:-5, 5:-5]
    mu2 = cv2.filter2D(img2, -1, window)[5:-5, 5:-5]
    mu1_sq = mu1 ** 2
    mu2_sq = mu2 ** 2
    mu1_mu2 = mu1 * mu2
    sigma1_sq = cv2.filter2D(img1 ** 2, -1, window)[5:-5, 5:-5] - mu1_sq
    sigma2_sq = cv2.filter2D(img2 ** 2, -1, window)[5:-5, 5:-5] - mu2_sq
    sigma12 = cv2.filter2D(img1 * img2, -1, window)[5:-5, 5:-5] - mu1_mu2

    ssim_map = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2)) / ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))
    return ssim_map.mean()

def calculate_psnr(img1, img2):
    mse = np.mean((img1.astype(np.float64) - img2.astype(np.float64)) ** 2)
    if mse == 0:
        return 100.0  # Images are identical
    return 20 * np.log10(255.0 / np.sqrt(mse))

def calculate_lpips(img1_pil, img2_pil):
    init_lpips()

    img1_tensor = pil_to_tensor(img1_pil) * 2 - 1
    img2_tensor = pil_to_tensor(img2_pil) * 2 - 1

    with torch.no_grad():
        distance = loss_fn_alex(img1_tensor, img2_tensor)

    return distance.item()

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/compare-base64', methods=['POST'])
def compare_images_base64():
    try:
        data = request.get_json()

        if 'generate' not in data or 'reference' not in data:
            return jsonify({'error': 'Missing image data'}), 400

        # generate: image generated by model (to be evaluated)
        # reference: target image (evaluation baseline)
        gen_b64 = data['generate']
        ref_b64 = data['reference']

        if ref_b64.startswith('data:'):
            ref_b64 = ref_b64.split(',')[1]
        if gen_b64.startswith('data:'):
            gen_b64 = gen_b64.split(',')[1]

        gen_data = base64.b64decode(gen_b64)
        ref_data = base64.b64decode(ref_b64)

        gen_img = Image.open(io.BytesIO(gen_data))
        ref_img = Image.open(io.BytesIO(ref_data))

        if gen_img.size != ref_img.size:
            ref_img = ref_img.resize(gen_img.size, Image.LANCZOS)

        gen_cv = np.array(gen_img.convert('RGB'))
        ref_cv = np.array(ref_img.convert('RGB'))

        msssim_value = calculate_msssim(gen_cv, ref_cv)
        psnr_value = calculate_psnr(gen_cv, ref_cv)
        lpips_value = calculate_lpips(gen_img, ref_img)

        metrics = {
            'msssim': round(msssim_value, 6),
            'psnr': round(psnr_value, 2),
            'lpips': round(lpips_value, 6)
        }

        return jsonify({'metrics': metrics})

    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    init_lpips()
    print("Initializing LPIPS model...")
    print("Starting server at http://localhost:5000")
    app.run(debug=True, host='0.0.0.0', port=5000)
